### PR TITLE
chore: add catalog info and python upgrade file

### PR DESCRIPTION
**Pull request by ichintanjoshi**
## Description

- Add catalog-info.yaml
- Add python upgrade file

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ichintanjoshi! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @ichintanjoshi! Just flagging that there's a failing check on this one.

**Comment by ichintanjoshi** [comment]
@mphilbrick211 it's codecov related, I am not sure how to fix it, I'll ask in the community

**Comment by mphilbrick211** [comment]
> @mphilbrick211 it's codecov related, I am not sure how to fix it, I'll ask in the community

Hi @ichintanjoshi! Just checking in to see if you were able to find help? If not, I can check with Axim.

**Comment by ichintanjoshi** [comment]
> > @mphilbrick211 it's codecov related, I am not sure how to fix it, I'll ask in the community
> 
> Hi @ichintanjoshi! Just checking in to see if you were able to find help? If not, I can check with Axim.

Hi @mphilbrick211  suggestions I got was to re-run it, so I've added some changes that were suggested in other branches, it should trigger a re-run on the checks.

**Review by feanil — APPROVED** [review]

**Pull request merged**
